spring.application.name=live-chat-backend

spring.datasource.url = jdbc:mysql://localhost:3306/livechat
spring.datasource.username = root
spring.datasource.password = TheAditya


spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
file.upload-dir=uploads

server.address=0.0.0.0